version: '2'

services:

  explorer:
    build:
      context: ../
      dockerfile: docker/explorer/Dockerfile
    ports:
      - "5000:5000"
    networks:
      main:
        ipv4_address: 10.5.0.5
        aliases:
          - explorer

  elements:
    build:
      context: ../
      dockerfile: docker/elements/Dockerfile
    volumes:
      - ../.explorer-data/elementsregtest:/root/.elements
    expose:
      - "7041"
    ports:
      - "7041:7041"
    networks:
      main:
        aliases:
          - elements

  bitcoin:
    build:
      context: ../
      dockerfile: docker/bitcoin/Dockerfile
    volumes:
      - ../.explorer-data/bitcoin:/root/.bitcoin
      - ../.explorer-data/testnet3:/root/.testnet3
    expose:
      - "8532"
      - "18532"
    ports:
      - "8532:8532"
      - "18532:18532"
    networks:
      main:
        aliases:
          - bitcoin

networks:
  main:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
